owner-repo: &owner-repo
  owner-repo: palantir/witchcraft-go-logging

version: 2.1

orbs:
  go: palantir/go@0.0.5
  godel: palantir/godel@0.0.2

all-tags-filter: &all-tags-filter
  filters:
    tags:
      only: /.*/

workflows:
  version: 2
  verify-test:
    jobs:
      - godel/verify:
          <<: *all-tags-filter
          name: verify
          executor:
            name: go/golang-1_11
            <<: *owner-repo
      - godel/test:
          <<: *all-tags-filter
          name: test-go-1.11
          executor:
            name: go/golang-1_11
            <<: *owner-repo
      - godel/test:
          <<: *all-tags-filter
          name: test-go-1.10
          executor:
            name: go/golang-1_10
            <<: *owner-repo
      - godel/test:
          <<: *all-tags-filter
          name: test-go-1.9
          executor:
            name: go/golang-1_9
            <<: *owner-repo
