version: 1
projects:
  conjure:
    output-dir: ./conjure
    ir-locator: https://palantir.bintray.com/releases/com/palantir/witchcraft/api/witchcraft-logging-api/1.0.0-rc1/witchcraft-logging-api-1.0.0-rc1.conjure.json
