products:
  wlog:
    build:
      main-pkg: ./wlog-tmpl/wlog
      version-var: main.version
      os-archs:
        - os: darwin
          arch: amd64
        - os: linux
          arch: amd64
    dist:
      disters:
        os-arch-bin:
          type: os-arch-bin
          config:
            os-archs:
              - os: darwin
                arch: amd64
              - os: linux
                arch: amd64
    publish: {}
product-defaults:
  publish:
    group-id: com.palantir.witchcraft.logging
